// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrescriptionList.Models;

#nullable disable

namespace PrescriptionList.Migrations
{
    [DbContext(typeof(PrescriptionContext))]
    [Migration("20250928022300_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PrescriptionList.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Cost = 19.99m,
                            FillStatus = "New",
                            MedicationName = "Atorvastatin",
                            RequestTime = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Cost = 12.50m,
                            FillStatus = "Filled",
                            MedicationName = "Metformin",
                            RequestTime = new DateTime(2025, 9, 5, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Cost = 8.75m,
                            FillStatus = "Pending",
                            MedicationName = "Lisinopril",
                            RequestTime = new DateTime(2025, 9, 10, 8, 15, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
